"""Public oracle for the orbit-harmonics Hilbert series of a matrix locus.

The target of problem 15 is the Hilbert series of the graded ring obtained by
applying orbit harmonics to the involution matrix locus

    M_{n,a} = { pi in S_n : pi^2 = id, fix(pi) = a } subset C^{n x n}.

For a finite point locus ``X subset C^N`` with vanishing ideal ``I(X)``, orbit
harmonics replaces ``I(X)`` by the ideal ``gr I(X)`` generated by the top-degree
components of its elements. The quotient ``R(X) = C[x]/gr I(X)`` is graded, is
isomorphic to ``C[X]`` as an (ungraded) module, and its Hilbert function is

    dim R(X)_d = dim V_d - dim V_{d-1},        V_d = { f|_X : deg f <= d },

the filtration of the function space ``C[X]`` by the degree needed to realize a
function. This module computes that filtration directly, which is the definition
of the target rather than a formula for it.

Two reductions make the computation finite and small. Every point of ``X`` is a
0/1 matrix with one 1 per row and column, so a monomial restricted to ``X`` is the
indicator ``[S subset pi]`` of its support ``S``, which vanishes unless ``S`` is a
partial permutation matrix. Hence

    V_d = span { [S subset pi] : S a partial permutation, |S| <= d }.

When ``X`` consists of involutions, ``[S subset pi] = [sym(S) subset pi]`` for the
symmetric closure ``sym(S) = S union S^T``, so the spanning set collapses to
*partial involutions* ``P`` -- disjoint 2-cycles and fixed points -- and the least
degree realizing ``[P subset pi]`` is

    wt(P) = #{2-cycles of P} + #{fixed points of P},

one variable per 2-cycle (either off-diagonal cell) and one per diagonal cell.

``dim V_d`` is then the rank of the 0/1 matrix whose rows are those indicators and
whose columns are the points of ``X``. The fast generator computes ranks by
blocked Gauss--Jordan elimination modulo two primes and requires agreement. That
agreement is a consistency check, not an exact certificate. The published
``certify_exact.py`` independently recomputes every scored rank through ``n=10``
by a proof-enabled sparse row echelon form over ``Q`` and writes
``data/exact_certificate.json``. The same code with
``spanning="permutation"`` computes the Hilbert series of the *full* permutation
matrix locus, whose answer is known (``sum_w q^{n - lis(w)}``, Rhoades), which is
how the implementation is validated on a locus other than the one it is used for.

The scored evaluator never imports this module; it only reads the published
targets.
"""
from __future__ import annotations

from fractions import Fraction
from itertools import permutations

import numpy as np

PROBLEM_ID = 15
PROBLEM_NAME = "inv_orbit_harmonics_hilbert_q_stat"

# Two primes for the modular ranks. The basis rejects loci for which
# ``m * (p - 1)**2 < 2**53`` does not hold, so every integer accumulated by the
# float64 matmuls is represented exactly.
PRIMES = (524287, 524269)
CHUNK_ROWS = 2048
PANEL_ROWS = 128
FLOAT64_EXACT_INTEGER_LIMIT = 1 << 53


def _float64_exact_inner_limit(prime: int) -> int:
    """Largest dot-product length whose unreduced integer sum is exact."""
    return (FLOAT64_EXACT_INTEGER_LIMIT - 1) // (prime - 1) ** 2


def float64_modular_point_limit() -> int:
    """Largest locus guaranteed exact for every configured modular prime."""
    return min(_float64_exact_inner_limit(prime) for prime in PRIMES)


# ---------------------------------------------------------------------------
# The spanning indicators
# ---------------------------------------------------------------------------


def _cell_indicators(points, n: int) -> dict:
    """``{(i, j): boolean vector [pi(i) = j]}`` over the ordered locus ``points``."""
    images = np.array(points, dtype=np.int64)  # (m, n), 1-based images
    return {
        (i, j): images[:, i - 1] == j
        for i in range(1, n + 1)
        for j in range(1, n + 1)
    }


def iter_indicators_of_weight(points, n: int, *, spanning: str, weight: int):
    """Yield the indicator of every spanning monomial of weight exactly ``weight``.

    ``spanning="involution"`` walks the partial involutions ``P`` ordered by the
    minimum of each block; ``spanning="permutation"`` walks the partial
    permutations ordered by row. Both visit each support exactly once. A branch
    whose indicator is already identically zero is pruned, since every extension of
    it is zero as well.
    """
    if spanning not in ("involution", "permutation"):
        raise ValueError(f"unknown spanning set: {spanning!r}")
    cell = _cell_indicators(points, n)
    used = [False] * (n + 2)

    def walk_involution(start: int, depth: int, vector):
        if depth == weight:
            yield vector
            return
        for i in range(start, n + 1):
            if used[i]:
                continue
            used[i] = True
            for j in (i, *range(i + 1, n + 1)):
                if used[j] and j != i:
                    continue
                extended = vector & cell[(i, j)]
                if extended.any():
                    used[j] = True
                    yield from walk_involution(i + 1, depth + 1, extended)
                    if j != i:
                        used[j] = False
            used[i] = False

    def walk_permutation(start: int, depth: int, vector):
        if depth == weight:
            yield vector
            return
        for i in range(start, n + 1):
            for j in range(1, n + 1):
                if used[j]:
                    continue
                extended = vector & cell[(i, j)]
                if extended.any():
                    used[j] = True
                    yield from walk_permutation(i + 1, depth + 1, extended)
                    used[j] = False

    walk = walk_involution if spanning == "involution" else walk_permutation
    yield from walk(1, 0, np.ones(len(points), dtype=bool))


# ---------------------------------------------------------------------------
# Modular rank: blocked Gauss--Jordan over F_p
# ---------------------------------------------------------------------------


class _ModularBasis:
    """A row-reduced echelon basis over ``F_p``, grown block by block.

    Reducing a new block against the basis is a single matmul because the basis is
    kept *reduced*: with ``B[:, pivots] = I``, the reduction of a row ``v`` is
    ``v - v[pivots] @ B``. Only the small panels are eliminated entry by entry, so
    the bulk of the elimination stays in BLAS.
    """

    def __init__(self, width: int, prime: int) -> None:
        limit = _float64_exact_inner_limit(prime)
        if width > limit:
            raise ValueError(
                f"float64 modular elimination with prime {prime} supports at most "
                f"{limit} points, got {width}; use exact=True or a safe modular backend"
            )
        self.width = width
        self.prime = prime
        self.rows = np.zeros((0, width), dtype=np.float64)
        self.pivots: list[int] = []

    @property
    def rank(self) -> int:
        return len(self.pivots)

    def _reduce(self, block):
        if self.pivots:
            block = (block - block[:, self.pivots] @ self.rows) % self.prime
        return block[block.any(axis=1)]

    def _absorb_panel(self, panel) -> bool:
        prime = self.prime
        new: list[np.ndarray] = []
        new_pivots: list[int] = []
        for row in panel:
            for pivot, earlier in zip(new_pivots, new):
                if row[pivot]:
                    row = (row - row[pivot] * earlier) % prime
            nonzero = np.flatnonzero(row)
            if not nonzero.size:
                continue
            pivot = int(nonzero[0])
            row = (row * pow(int(row[pivot]), -1, prime)) % prime
            for index, earlier in enumerate(new):
                if earlier[pivot]:
                    new[index] = (earlier - earlier[pivot] * row) % prime
            new.append(row)
            new_pivots.append(pivot)
        if not new:
            return False
        fresh = np.array(new, dtype=np.float64)
        if self.pivots:
            self.rows = (self.rows - self.rows[:, new_pivots] @ fresh) % prime
        self.rows = np.vstack([self.rows, fresh])
        self.pivots.extend(new_pivots)
        return True

    def _add_block(self, block) -> None:
        # One matmul over the whole block first: it discards the rows that are
        # already in the span, which is nearly all of them once the rank saturates.
        # A panel needs reducing again only after an earlier panel of the same block
        # has enlarged the basis, which is rare once the rank saturates.
        block = self._reduce(block)
        stale = False
        for offset in range(0, len(block), PANEL_ROWS):
            panel = block[offset:offset + PANEL_ROWS]
            if stale:
                panel = self._reduce(panel)
            stale = self._absorb_panel(panel) or stale

    def add_stream(self, indicators) -> None:
        """Add 0/1 vectors from an iterator, in chunks, until the stream is empty."""
        chunk: list = []
        for vector in indicators:
            chunk.append(vector)
            if len(chunk) == CHUNK_ROWS:
                self._add_block(np.array(chunk, dtype=np.float64))
                chunk = []
        if chunk:
            self._add_block(np.array(chunk, dtype=np.float64))


def _hilbert_series_modular(points, n: int, *, spanning: str, max_weight: int, prime: int):
    basis = _ModularBasis(len(points), prime)
    series: list[int] = []
    for weight in range(max_weight + 1):
        previous = basis.rank
        basis.add_stream(
            iter_indicators_of_weight(points, n, spanning=spanning, weight=weight)
        )
        series.append(basis.rank - previous)
        if basis.rank == len(points):
            return series
    raise RuntimeError(
        f"the spanning set of weight <= {max_weight} does not span C[X]: "
        f"rank {basis.rank} of {len(points)}"
    )


# ---------------------------------------------------------------------------
# Exact rank over Q, for cross-checking the modular ranks on small loci
# ---------------------------------------------------------------------------


def _hilbert_series_exact(points, n: int, *, spanning: str, max_weight: int):
    basis: list[list[Fraction]] = []
    pivots: list[int] = []
    series: list[int] = []
    for weight in range(max_weight + 1):
        previous = len(pivots)
        for vector in iter_indicators_of_weight(points, n, spanning=spanning, weight=weight):
            row = [Fraction(int(bit)) for bit in vector]
            for pivot, earlier in zip(pivots, basis):
                if row[pivot]:
                    factor = row[pivot]
                    row = [value - factor * other for value, other in zip(row, earlier)]
            pivot = next((index for index, value in enumerate(row) if value), None)
            if pivot is None:
                continue
            inverse = 1 / row[pivot]
            row = [value * inverse for value in row]
            basis = [
                [value - earlier[pivot] * other for value, other in zip(earlier, row)]
                if earlier[pivot]
                else earlier
                for earlier in basis
            ]
            basis.append(row)
            pivots.append(pivot)
        series.append(len(pivots) - previous)
        if len(pivots) == len(points):
            return series
    raise RuntimeError("the spanning set does not span C[X]")


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def hilbert_series(points, n: int, *, spanning: str = "involution", max_weight: int, exact: bool = False):
    """``[dim R(X)_0, dim R(X)_1, ...]`` for the locus of the given points.

    The modular ranks are computed with both primes of ``PRIMES`` and must agree.
    This is the fast generation path; use ``certify_exact.py`` for the independent
    proof-enabled computation over the rational field.
    """
    points = list(points)
    if exact:
        return _hilbert_series_exact(points, n, spanning=spanning, max_weight=max_weight)
    series = [
        _hilbert_series_modular(points, n, spanning=spanning, max_weight=max_weight, prime=prime)
        for prime in PRIMES
    ]
    if series[0] != series[1]:
        raise RuntimeError(f"modular ranks disagree between primes: {series}")
    return series[0]


def iter_involution_images(n: int, a: int):
    """The images ``(pi(1), ..., pi(n))`` of every involution in ``M_{n,a}``.

    Kept here so the oracle is self-contained; the generator checks that this
    agrees with the public enumerator in ``qtbench.combinatorics``.
    """

    def walk(free: tuple[int, ...], fixed_left: int):
        if not 0 <= fixed_left <= len(free) or (len(free) - fixed_left) % 2:
            return
        if not free:
            yield ()
            return
        smallest, rest = free[0], free[1:]
        if fixed_left:
            for tail in walk(rest, fixed_left - 1):
                yield ((smallest, smallest), *tail)
        for index, partner in enumerate(rest):
            for tail in walk(rest[:index] + rest[index + 1:], fixed_left):
                yield ((smallest, partner), *tail)

    for cycles in walk(tuple(range(1, n + 1)), a):
        images = [0] * n
        for i, j in cycles:
            images[i - 1] = j
            images[j - 1] = i
        yield tuple(images)


def involution_hilbert_series(n: int, a: int, *, exact: bool = False):
    """``Hilb(R(M_{n,a}); q)`` as a coefficient list, index = degree in ``q``.

    A partial involution is contained in some member of ``M_{n,a}`` only if it has
    at most ``a`` fixed points and at most ``(n - a) / 2`` 2-cycles, so its weight
    is at most ``(n + a) / 2``; that bound is attained by the partial involutions
    that pin down a single point, which is why the spanning set of that weight
    already spans ``C[M_{n,a}]``.
    """
    if not 0 <= a <= n or (n - a) % 2:
        raise ValueError(
            f"M_{{{n},{a}}} is empty: need 0 <= a <= n and a congruent to n (mod 2)"
        )
    return hilbert_series(
        iter_involution_images(n, a),
        n,
        spanning="involution",
        max_weight=(n + a) // 2,
        exact=exact,
    )


def permutation_hilbert_series(n: int, *, exact: bool = False):
    """``Hilb(R(S_n); q)`` for the *full* permutation matrix locus.

    Used only to validate the machinery: Rhoades proved this equals
    ``sum_{w in S_n} q^{n - lis(w)}``, an answer the involution computation never
    sees.
    """
    return hilbert_series(
        permutations(range(1, n + 1)), n, spanning="permutation", max_weight=n, exact=exact
    )
