"""Parking functions paired with a Tamari-smaller Dyck path, and their statistics.

Following Bergeron and Preville-Ratelle (see the problem statement for
references), a **Dyck path** of height ``n`` is encoded by the weakly increasing
sequence ``alpha = (a_1, ..., a_n)`` with ``0 <= a_i <= i - 1``, where ``a_i`` is
the number of cells to the left of the path at height ``i``. A **parking
function** ``f = (f_1, ..., f_n)`` of length ``n`` is a sequence of nonnegative
integers whose weakly increasing rearrangement ``beta(f)`` is a Dyck path; that
rearrangement is its **shape**.

The **Tamari order** on Dyck paths is generated by: whenever ``a_{i-1} < a_i``,
let ``(a_i, ..., a_k)`` be the *primitive* subsequence starting at ``i`` (the
longest run with ``a_j - a_i < j - i`` for ``i < j <= k``), and set
``alpha <= beta`` for ``beta`` obtained by decreasing ``a_i, ..., a_k`` by one.
The maximum is ``(0, ..., 0)`` and the minimum is ``(0, 1, ..., n-1)``. The
lattice is **not graded**, so ``d(alpha, beta)``, the length of the longest chain
from ``alpha`` up to ``beta``, is a genuine longest-path computation; when
``alpha`` is the minimum it equals ``area(beta) = binom(n,2) - sum_i b_i``.

An object of this family is a pair ``(f, alpha)`` with ``alpha <= beta(f)``. The
two public statistics are the chain length ``d(alpha, beta(f))`` and the parking
function statistic ``dinv(f)``; the trivariate target grades them by ``q1`` and
``q2`` and the missing statistic by ``q3``.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import cache, cached_property
from typing import Iterator

SEPARATOR = "|"

TamariParkingWord = str


# ---------------------------------------------------------------------------
# Dyck paths and the Tamari order
# ---------------------------------------------------------------------------


def is_dyck_vector(alpha: tuple[int, ...]) -> bool:
    """Whether ``alpha`` is weakly increasing with ``0 <= a_i <= i - 1``."""
    return all(
        0 <= value <= i - 1 and (i == 1 or alpha[i - 2] <= value)
        for i, value in enumerate(alpha, start=1)
    )


@cache
def enumerate_dyck_vectors(n: int) -> tuple[tuple[int, ...], ...]:
    """Every Dyck path of height ``n``, as a weakly increasing ``a``-vector."""
    if n < 1:
        raise ValueError("size must be positive")
    out: list[tuple[int, ...]] = []
    current: list[int] = []

    def rec(i: int) -> None:
        if i > n:
            out.append(tuple(current))
            return
        low = current[-1] if current else 0
        for value in range(low, i):
            current.append(value)
            rec(i + 1)
            current.pop()

    rec(1)
    return tuple(out)


def _primitive_end(alpha: tuple[int, ...], i: int) -> int:
    """The last index ``k`` of the primitive subsequence of ``alpha`` starting at ``i``."""
    n = len(alpha)
    k = i
    while k < n and alpha[k] - alpha[i - 1] < (k + 1) - i:
        k += 1
    return k


def tamari_up_covers(alpha: tuple[int, ...]) -> tuple[tuple[int, ...], ...]:
    """The Dyck paths that cover ``alpha`` from above in the Tamari order."""
    out = []
    for i in range(2, len(alpha) + 1):
        if alpha[i - 2] < alpha[i - 1]:
            k = _primitive_end(alpha, i)
            out.append(
                tuple(
                    value - 1 if i <= j <= k else value
                    for j, value in enumerate(alpha, start=1)
                )
            )
    return tuple(out)


@cache
def tamari_chain_length(alpha: tuple[int, ...], beta: tuple[int, ...]) -> int | None:
    """Length of the longest Tamari chain from ``alpha`` up to ``beta``, or ``None``.

    Going up never increases an entry, so any ``gamma`` on a chain from ``alpha``
    to ``beta`` satisfies ``beta <= gamma <= alpha`` entrywise; that cheap
    necessary condition prunes the search to the entrywise interval.
    """
    if alpha == beta:
        return 0
    if any(a < b for a, b in zip(alpha, beta)):
        return None
    best = None
    for cover in tamari_up_covers(alpha):
        if any(c < b for c, b in zip(cover, beta)):
            continue
        below = tamari_chain_length(cover, beta)
        if below is not None and (best is None or below + 1 > best):
            best = below + 1
    return best


def tamari_leq(alpha: tuple[int, ...], beta: tuple[int, ...]) -> bool:
    """Whether ``alpha <= beta`` in the Tamari order."""
    return tamari_chain_length(alpha, beta) is not None


@cache
def tamari_down_set(beta: tuple[int, ...]) -> tuple[tuple[int, ...], ...]:
    """Every Dyck path ``alpha`` with ``alpha <= beta``, in lexicographic order."""
    return tuple(
        alpha for alpha in enumerate_dyck_vectors(len(beta)) if tamari_leq(alpha, beta)
    )


def dyck_area(beta: tuple[int, ...]) -> int:
    """``area(beta) = binom(n, 2) - sum_i b_i``, the chain length from the minimum."""
    n = len(beta)
    return n * (n - 1) // 2 - sum(beta)


# ---------------------------------------------------------------------------
# Parking functions
# ---------------------------------------------------------------------------


def parking_shape(f: tuple[int, ...]) -> tuple[int, ...]:
    """The weakly increasing rearrangement ``beta(f)`` of a parking function."""
    return tuple(sorted(f))


def is_parking_function(f: tuple[int, ...]) -> bool:
    """Whether the weakly increasing rearrangement of ``f`` is a Dyck path."""
    return all(value >= 0 for value in f) and is_dyck_vector(parking_shape(f))


def parking_dinv(f: tuple[int, ...]) -> int:
    """The ``dinv`` of a parking function.

    Let ``(a_i, b_i)`` be the lexicographic rearrangement of ``(i, f_i)`` ordered
    first by value, and ``c_i = i - b_i``. Then ``dinv`` counts the pairs
    ``i < j`` with either ``c_i = c_j`` and ``a_i < a_j``, or ``c_i - c_j = 1``
    and ``a_i > a_j``.
    """
    pairs = sorted((value, position) for position, value in enumerate(f, start=1))
    a = [position for _value, position in pairs]
    c = [i - value for i, (value, _position) in enumerate(pairs, start=1)]
    n = len(f)
    return sum(
        1
        for i in range(n)
        for j in range(i + 1, n)
        if (c[i] == c[j] and a[i] < a[j]) or (c[i] - c[j] == 1 and a[i] > a[j])
    )


# ---------------------------------------------------------------------------
# The object family
# ---------------------------------------------------------------------------


def _parse(encoding: str):
    parking_text, alpha_text = encoding.split(SEPARATOR)
    f = tuple(int(piece) for piece in parking_text.split(",")) if parking_text else ()
    alpha = tuple(int(piece) for piece in alpha_text.split(",")) if alpha_text else ()
    return f, alpha


def _encode(f, alpha) -> str:
    parking_text = ",".join(str(value) for value in f)
    alpha_text = ",".join(str(value) for value in alpha)
    return f"{parking_text}{SEPARATOR}{alpha_text}"


def is_tamari_parking_pair(encoding: str) -> bool:
    """Whether ``encoding`` is a valid ``f|alpha`` pair with ``alpha <= beta(f)``.

    The order test is a search in the Tamari lattice, so this is only practical
    for the small sizes of the public data; large probe objects are built valid
    by construction instead.
    """
    if not isinstance(encoding, str) or encoding.count(SEPARATOR) != 1:
        return False
    try:
        f, alpha = _parse(encoding)
    except ValueError:
        return False
    if not f or len(alpha) != len(f):
        return False
    if not is_parking_function(f) or not is_dyck_vector(alpha):
        return False
    return tamari_leq(alpha, parking_shape(f))


@dataclass(frozen=True, init=False)
class TamariParkingPair:
    """A parking function together with a Tamari-smaller Dyck path.

    Encoded as ``f + "|" + alpha`` where ``f`` lists the parking function values
    and ``alpha`` the ``a``-vector of a Dyck path with ``alpha <= beta(f)``.
    Public benchmark code exposes only structural data and the two public
    statistics ``chain`` and ``dinv``; the unknown third statistic belongs to the
    discovery task.
    """

    encoding: str
    n: int

    def __init__(self, encoding: str, *, validate: bool = True) -> None:
        if validate and not is_tamari_parking_pair(encoding):
            raise ValueError(f"not a Tamari parking pair: {encoding!r}")
        object.__setattr__(self, "encoding", encoding)
        object.__setattr__(self, "n", encoding.split(SEPARATOR)[0].count(",") + 1)

    @property
    def size(self) -> int:
        """Length of the parking function, ``n``."""
        return self.n

    @cached_property
    def parking_function(self) -> tuple[int, ...]:
        """The parking function ``f``."""
        return _parse(self.encoding)[0]

    @cached_property
    def alpha(self) -> tuple[int, ...]:
        """The ``a``-vector of the smaller Dyck path."""
        return _parse(self.encoding)[1]

    @cached_property
    def beta(self) -> tuple[int, ...]:
        """The shape ``beta(f)``, the weakly increasing rearrangement of ``f``."""
        return parking_shape(self.parking_function)

    @cached_property
    def minimum(self) -> tuple[int, ...]:
        """The Tamari minimum ``(0, 1, ..., n-1)`` of this size."""
        return tuple(range(self.n))

    def area(self) -> int:
        """``area(beta(f))``: the chain length from the Tamari minimum to the shape."""
        return dyck_area(self.beta)

    def chain(self) -> int:
        """``d(alpha, beta(f))``: the length of the longest Tamari chain.

        The two extremes are closed forms -- ``0`` when ``alpha`` is the shape and
        ``area(beta(f))`` when it is the Tamari minimum -- and anything in between
        searches the Tamari interval, which is only cheap for small sizes.
        """
        if self.alpha == self.beta:
            return 0
        if self.alpha == self.minimum:
            return self.area()
        return tamari_chain_length(self.alpha, self.beta)

    def dinv(self) -> int:
        """``dinv(f)``, the parking function inversion statistic."""
        return parking_dinv(self.parking_function)

    def to_jsonable(self) -> str:
        return self.encoding


def tamari_parking_chain(encoding: str) -> int:
    """``d(alpha, beta(f))`` of the pair given by ``encoding``."""
    return TamariParkingPair(encoding, validate=False).chain()


def tamari_parking_dinv(encoding: str) -> int:
    """``dinv(f)`` of the pair given by ``encoding``."""
    return TamariParkingPair(encoding, validate=False).dinv()


def tamari_parking_size(encoding_or_object) -> int:
    """Length ``n`` (module-level, for the value/resource gate)."""
    if isinstance(encoding_or_object, TamariParkingPair):
        return encoding_or_object.n
    return encoding_or_object.split(SEPARATOR)[0].count(",") + 1


def _iter_parking_functions(n: int) -> Iterator[tuple[int, ...]]:
    """Yield every parking function of length ``n`` once.

    A prefix extends to a parking function exactly when its ``r``-th smallest
    value leaves room for the values above it, i.e. ``s_r <= n - (j - r) - 1``.
    """
    current: list[int] = []

    def extendable() -> bool:
        sorted_prefix = sorted(current)
        j = len(sorted_prefix)
        return all(
            value <= n - (j - r) - 1 for r, value in enumerate(sorted_prefix, start=1)
        )

    def rec(position: int) -> Iterator[tuple[int, ...]]:
        if position > n:
            yield tuple(current)
            return
        for value in range(n):
            current.append(value)
            if extendable():
                yield from rec(position + 1)
            current.pop()

    yield from rec(1)


def iter_tamari_parking_pairs(n: int) -> Iterator[TamariParkingPair]:
    """Yield every pair ``(f, alpha)`` with ``alpha <= beta(f)`` once, streaming."""
    if n < 1:
        raise ValueError("size must be positive")
    for f in _iter_parking_functions(n):
        for alpha in tamari_down_set(parking_shape(f)):
            yield TamariParkingPair(_encode(f, alpha), validate=False)


@cache
def enumerate_tamari_parking_pairs(n: int) -> tuple[TamariParkingPair, ...]:
    """All pairs of size ``n`` (cached; use the iterator for large sizes)."""
    return tuple(iter_tamari_parking_pairs(n))


def tamari_parking_count(n: int) -> int:
    """The number of pairs, ``2^n (n+1)^{n-2}``, by streaming enumeration."""
    return sum(1 for _ in iter_tamari_parking_pairs(n))


def canonical_tamari_parking_pair(f, at_minimum: bool = False) -> TamariParkingPair:
    """A canonical pair on the parking function ``f``, built in linear time.

    ``alpha`` is either the shape ``beta(f)`` itself or the Tamari minimum
    ``(0, 1, ..., n-1)``, both of which satisfy ``alpha <= beta(f)`` by
    construction and have a closed-form chain length. Used to build large valid
    objects for the resource and value gates without searching the
    (exponentially large) Tamari lattice.
    """
    f = tuple(int(value) for value in f)
    if not f or not is_parking_function(f):
        raise ValueError("not a parking function")
    beta = parking_shape(f)
    alpha = tuple(range(len(f))) if at_minimum else beta
    return TamariParkingPair(_encode(f, alpha), validate=False)


def intermediate_tamari_parking_pairs(n: int, choices) -> tuple[TamariParkingPair, ...]:
    """Pairs whose ``alpha`` is neither the shape nor the Tamari minimum.

    ``choices`` supplies one nonnegative integer per step; step ``j`` moves to
    up-cover number ``choices[j]`` modulo the number of covers. That walks a
    Tamari chain ``minimum = g_0 < g_1 < ... < g_L``, so taking ``beta = g_L`` and
    ``alpha`` a third and two thirds of the way up gives ``alpha <= beta`` by
    construction, at cost linear in ``len(choices)``. Unlike the two extremes of
    ``canonical_tamari_parking_pair`` these intervals have no closed-form chain
    length, so ``chain()`` on them is a genuine longest-path search; that is what
    makes them the useful large probes for the resource gates.

    ``beta`` is weakly increasing, hence itself a parking function of shape
    ``beta``, and so is its reverse. Returns ``()`` for ``n < 4``, where the chain
    from the minimum can be too short to have an interior.
    """
    if n < 4:
        return ()
    chain = [tuple(range(n))]
    for choice in choices:
        covers = tamari_up_covers(chain[-1])
        if not covers:
            break
        chain.append(covers[choice % len(covers)])
    # the walk reaches the maximum in at least binom(n,2)/(n-1) >= 2 moves, so the
    # chain always has an interior index to clamp onto
    last = len(chain) - 1
    beta = chain[-1]
    return tuple(
        TamariParkingPair(_encode(f, chain[min(max(index, 1), last - 1)]), validate=False)
        for index in (last // 3, 2 * last // 3)
        for f in (beta, beta[::-1])
    )
